name: download-artifacts

description: Download dependencies (artifacts)

inputs:
  target-device: {type: string, required: true}
  git_sha: {type: string, required: true}
  inter_repos_ro_access_token: {required: true}
  platform: {type: string, required: true}
  dest-dir: {type: string, required: true}

runs:
  using: composite
  steps:

    - id: cache
      name: Cache conda artifacts
      uses: actions/cache@v3
      with:
        key: "nv-legate/${{ inputs.platform }}-legate.core.internal@${{ inputs.git_sha }}-${{ inputs.target-device }}"
        path: ${{ inputs.dest-dir }}

    - if: steps.cache.outputs.cache-hit != 'true'
      name: Download conda artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.inter_repos_ro_access_token }}
        path: ${{ inputs.dest-dir }}
        repo: nv-legate/legate.core.internal
        check_artifacts: true
        # search_artifacts: true
        commit: ${{ inputs.git_sha }}
        workflow_conclusion: success
        workflow: "ci-gh.yml"
        name: "${{ inputs.platform }}-legate.core.internal-${{ inputs.target-device }}-release-gcc-${{ inputs.git_sha }}"
        # name_is_regexp: true
        skip_unpack: true
        if_no_artifact_found: fail
        allow_forks: false

    - if: steps.cache.outputs.cache-hit != 'true'
      name: Unpack artifact
      shell: bash --noprofile --norc -xeuo pipefail {0}
      run: |
        cd ${{ inputs.dest-dir }}
        unzip *.zip
