name: Build Nightly release package

concurrency:
  group: ci-nightly-release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # Nightly at 11:00 PM

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        target-device:
          - gpu
          - cpu
        upload-enabled:
          - true
          - false
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      target-device: ${{ matrix.target-device }}
      platform: linux
      build-type: release
      upload-enabled: ${{ matrix.upload-enabled }}
      dependencies-workflow: "ci-gh-nightly-release.yml"
    secrets: inherit
