name: Build Release package

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-build-and-test-on-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "cpp-branch-*"
      - "main"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - linux-aarch64
        target-device:
          - gpu
          - cpu
        upload-enabled:
          - false
        python-version:
          - "3.12"
        exclude:
          - platform: linux-aarch64
            target-device: gpu
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      build-type: release
      platform: ${{ matrix.platform }}
      python-version: "3.10"
      target-device: ${{ matrix.target-device }}
      upload-enabled: ${{ matrix.upload-enabled }}
      waive-gpu-tests: ${{ github.workflow == 'Build Release package' && matrix.platform == 'linux-aarch64' }}
    secrets: inherit
