name: Build CI package

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-build-and-test-on-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "cpp-branch-*"
      - "main"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - linux-aarch64
        target-device:
          - gpu
          - cpu
        upload-enabled:
          - false
        python-version:
          - "3.12"
        exclude:
          - platform: linux-aarch64
            target-device: gpu
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      build-type: ci
      platform: ${{ matrix.platform }}
      python-version: ${{ matrix.python-version }}
      target-device: ${{ matrix.target-device }}
      upload-enabled: ${{ matrix.upload-enabled }}
      waive-gpu-tests: ${{ github.workflow == 'Build Release package' && matrix.platform == 'linux-aarch64' }}
      refname: ${{ github.ref_name }}
      default-branch: ${{ github.event.repository.default_branch }}
    secrets: inherit

  tests-pass:
    if: always()
    needs:
      - build-and-test
    runs-on: linux-amd64-cpu4
    steps:
      - name: Check job results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
