name: Build and test

concurrency:
  group: ci-build-and-test-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "cpp-branch-*"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        target-device:
          - gpu
          - cpu
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      target-device: ${{ matrix.target-device }}
      platform: linux
    secrets: inherit
