on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
      target-device:
        type: string
        required: true
      build-type:
        type: string
        required: true
      upload-enabled:
        type: boolean
        required: true
      dependencies-workflow:
        required: true
        type: string
        description: The workflow file name used by the dependency 

jobs:
  setup-build:
    name: Setup build
    runs-on: linux-amd64-cpu4
    outputs:
      runner_type: ${{ steps.set_runner.outputs.runner_type }}
    steps:
      - id: set_runner
        run: |
          if [ "${{ inputs.platform }}" = "linux" ]; then
            if [ "${{ github.repository_owner }}" = "nv-legate" ]; then
              echo "runner_type=linux-amd64-cpu16" >> $GITHUB_OUTPUT
            else
              echo "runner_type=ubuntu-latest" >> $GITHUB_OUTPUT
            fi
          elif [ "${{ inputs.platform }}" = "mac" ]; then
            echo "runner_type=macos-latest"  >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup-build
    name: "Build (${{ inputs.platform }}, ${{ inputs.target-device }}, ${{ inputs.build-type }})"
    uses:
      nv-legate/legate-gh-ci/.github/workflows/gh-build.yml@v1.4
    with:
      client-repo: ${{ github.event.repository.name }}
      target-device: ${{ inputs.target-device }}
      runs-on: ${{ needs.setup-build.outputs.runner_type }}
      build-type: ${{ inputs.build-type }}
      use-container: ${{ inputs.platform == 'linux' }}
      platform: ${{ inputs.platform }}
      dependencies-file: "cmake/versions.json"
      dependencies-workflow: ${{ inputs.dependencies-workflow }}
      legate-gh-ci-tag: "v1.4"
      build-mode: ""
      ucx-enabled: false
      upload-enabled: ${{ inputs.upload-enabled }}

    secrets: inherit

    
  upload:
    needs: build
    runs-on: linux-amd64-gpu-v100-earliest-1
    container:
      options: -u root
      image: condaforge/miniforge3:latest
  
    if: ${{ github.repository_owner == 'nv-legate' && inputs.upload-enabled == true }}
    steps:
      - name: Set environment variables
        shell: bash --noprofile --norc -xeuo pipefail {0}
        run: |
          UCX_STR=''
          BUILD_MODE=''
          BUILD_MODE_STR=""
          [ -n "${BUILD_MODE}" ] && BUILD_MODE_STR="-${BUILD_MODE}"
  
          echo "ARTIFACT_NAME=${{ inputs.platform }}-${{ inputs.build-type }}-${{ github.event.repository.name }}-${{ inputs.target-device }}${BUILD_MODE_STR}${UCX_STR}-${{ github.sha }}" >> $GITHUB_ENV
          echo "ARTIFACTS_DIR=${{ github.workspace }}/artifacts"  >> $GITHUB_ENV
          echo "OUTPUT_FOLDER=conda-build/cunumeric" >> $GITHUB_ENV
          echo "TARGET_PLATFORM=linux-64" >> $GITHUB_ENV
  
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACTS_DIR }}
  
      - name: Display structure of downloaded artifacts
        run: |
          ls -aR $ARTIFACTS_DIR

      - name: Get Build Date
        run: |
          echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Dump relevant environment variables
        run: |
          echo "ARTIFACTS_DIR=$ARTIFACTS_DIR" 
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" 
          echo "TARGET_PLATFORM=$TARGET_PLATFORM"
          echo "BUILD_DATE=$BUILD_DATE"

      - name: Upload to URM
        run: |
          apt-get update
          apt-get install -y curl
          for f in $(find $ARTIFACTS_DIR/$OUTPUT_FOLDER/$TARGET_PLATFORM/. -name 'cunumeric-*.tar.bz2')
          do
            fname=$(basename $f)
            echo "File to upload: $fname"
            curl -usvc-legate-github:${{ secrets.URM_ARTIFACT_TOKEN }} -T $f "https://urm.nvidia.com/artifactory/sw-legate-conda-local/${TARGET_PLATFORM}/$fname;buildType="Nightly";buildDate=$BUILD_DATE;automatedTestingPassed=0;sha=${{ github.sha }}";
          done

  setup-test:
    if: inputs.upload-enabled == false
    name: Setup test
    needs:
      - build
    runs-on: linux-amd64-cpu4
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          set -xeuo pipefail
          MATRIX_JSON='{"include": ['
          RUNNERS=(
            'linux-amd64-gpu-v100-latest-1:gpu:gpu:linux' 'linux-amd64-2gpu:gpu:2gpu:linux'
            'linux-amd64-cpu16:cpu:cpu:linux'
            'macos-latest:cpu:cpu:mac')
          TEST_CONFIGS=(
            '1 CPU test:test --cpus 1 --debug:cpu'
            '1 CPU test:test --cpus 1 --debug:gpu'
            '2 CPU test:test --cpus 2 --debug:cpu'
            '2 CPU test:test --cpus 2 --debug:gpu'
            # set the number of workers manually because nvidia runners report 6 gpus when onyl one is really available
            # this workaround can be removed when the number of available gpus is reported correctly (when we run on VMs)
            'GPU test:test --use cuda --gpus 1 -j 7 --debug:gpu'
            '2 GPU test:test --use cuda --gpus 2 --debug:2gpu'
            'OpenMP test:test --use openmp --omps 1 --ompthreads 2 --debug:gpu'
            'OpenMP test:test --use openmp --omps 1 --ompthreads 2 --debug:cpu'
            '2 NUMA OpenMPs test:test --use openmp --omps 2 --ompthreads 2 --numamem 2048 --debug:gpu'
            '2 NUMA OpenMPs test:test --use openmp --omps 2 --ompthreads 2 --numamem 2048 --debug:cpu'
            'Eager execution test:test --use eager --debug:gpu'
            'Eager execution test:test --use eager --debug:cpu'
            'mypy:mypy:cpu'
            'Documentation:docs:cpu'
            'Unit tests:unit:cpu'
          )
          for RUNNER in "${RUNNERS[@]}"; do
            IFS=':' read -ra RUNNER_INFO <<< "$RUNNER"
            RUNNER_NAME=${RUNNER_INFO[0]}
            RUNNER_TYPE=${RUNNER_INFO[1]}
            RUNNER_DEVICE=${RUNNER_INFO[2]}
            RUNNER_PLATFORM=${RUNNER_INFO[3]}
            if [[ "$RUNNER_TYPE" == "${{ inputs.target-device }}" && "$RUNNER_PLATFORM" == "${{ inputs.platform }}" ]]; then
              for TEST_CONFIG in "${TEST_CONFIGS[@]}"; do
                IFS=':' read -ra CONFIG_INFO <<< "$TEST_CONFIG"
                TEST_NAME=${CONFIG_INFO[0]}
                TEST_OPTIONS=${CONFIG_INFO[1]}
                TEST_TARGET_DEVICE=${CONFIG_INFO[2]}
                if [[ "$TEST_TARGET_DEVICE" == "$RUNNER_DEVICE" ]]; then
                  MATRIX_JSON+="{\"runner\": {\"name\": \"$RUNNER_NAME\", \"type\": \"$RUNNER_TYPE\", \"platform\": \"$RUNNER_PLATFORM\"}, \"test-config\": {\"name\": \"$TEST_NAME\", \"test-options\": \"$TEST_OPTIONS\"}},"
                fi
              done
            fi
          done
          MATRIX_JSON=$(echo "$MATRIX_JSON" | sed 's/,$//') # Remove the trailing comma
          MATRIX_JSON+=']}'
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  test:
    needs:
      - setup-test
    name: ${{ matrix.test-config.name }} (${{ inputs.platform }}, ${{ inputs.target-device }})

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup-test.outputs.matrix)}}

    uses:
      nv-legate/legate-gh-ci/.github/workflows/gh-test-within-container.yml@v1.4
    with:
      client-repo: ${{ github.event.repository.name }}
      build-type: ${{ inputs.build-type }}
      name: ${{ matrix.test-config.name }}
      target-device: ${{ inputs.target-device }}
      runs-on: ${{ matrix.runner.name }}
      has-gpu: ${{ matrix.runner.type == 'gpu' }}
      test-options: ${{ matrix.test-config.test-options }}
      platform: ${{ inputs.platform }}
      legate-gh-ci-tag: "v1.4"
      build-mode: ""
      ucx-enabled: false
      upload-enabled: ${{ inputs.upload-enabled }}
    secrets: inherit
