name: Test

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      target-device:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      has-gpu:
        required: true
        type: boolean
        description: "The runner has GPU(s)."
      test-options:
        required: true
        type: string
      platform:
        required: true
        type: string

env:
  ARTIFACT_NAME: "${{ inputs.platform }}-${{ github.event.repository.name }}-${{ inputs.target-device }}-${{ github.sha }}"
  ARTIFACTS_DIR: "${{ github.workspace }}/artifacts"

jobs:
  test:
    name: ${{ inputs.name }}
    if: github.repository_owner == 'nv-legate'
    runs-on: ${{ inputs.runs-on }}

    container:
      options: -u root --security-opt seccomp=unconfined
      image: condaforge/miniforge3:latest
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash --noprofile --norc -xeuo pipefail {0}

    steps:
      - if: inputs.has-gpu
        name: Run nvidia-smi to make sure GPU is working
        run: nvidia-smi

      # This step is needed to work around a github runner bug which causes the value of github.workspace to change over time.
      - name: Dump relevant enviornment variables
        run: |
          pwd
          echo "ARTIFACTS_DIR=$ARTIFACTS_DIR" >> $GITHUB_ENV
          echo ARTIFACT_NAME=$ARTIFACT_NAME
          echo Platform: ${{ inputs.platform }}

      - name: Dump CPU info
        run: |
          cat /proc/cpuinfo

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "${{ github.workspace }}/cunumeric.internal"
          persist-credentials: false

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACTS_DIR }}

      - name: Display structure of downloaded artifacts
        run: |
          pwd
          ls -lahR $ARTIFACTS_DIR

      - name: Run ${{ github.event.repository.name }} test / analysis
        run: |
          cd cunumeric.internal

          continuous_integration/scripts/entrypoint test-cunumeric ${{ inputs.test-options }}
